Repository thomhurst/TUnit, pull requests merged in 2025-03, with the labels that each got.

#1964 chore(deps): update microsoft.aspnetcore to v9 (major)
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/WebApp/WebApp.csproj
Labels: dependencies, renovate-bot, MAJOR

#1978 Remove Test/HookExecutor synchronous overloads and switch to ValueTasks
  TUnit.Core/AsyncConvert.cs
  TUnit.Core/Attributes/TestData/ClassDataSourceAttribute.cs
  TUnit.Core/Attributes/TestData/ClassDataSourceAttribute_2.cs
  TUnit.Core/Attributes/TestData/ClassDataSourceAttribute_3.cs
  TUnit.Core/Attributes/TestData/ClassDataSourceAttribute_4.cs
  TUnit.Core/Attributes/TestData/ClassDataSourceAttribute_5.cs
  TUnit.Core/Attributes/TestData/MatrixAttribute.cs
  TUnit.Core/Attributes/TestData/MatrixDataSourceAttribute.cs
  TUnit.Core/Attributes/TestData/MatrixRangeAttribute.cs
  TUnit.Core/BeforeTestContext.cs
  TUnit.Core/Context.cs
  TUnit.Core/DiscoveredTest.cs
  TUnit.Core/Executors/DefaultExecutor.cs
  TUnit.Core/Executors/GenericAbstractExecutor.cs
  TUnit.Core/Executors/STAThreadExecutor.cs
  TUnit.Core/FailedTestMetadata.cs
  TUnit.Core/Hooks/AfterAssemblyHookMethod.cs
  TUnit.Core/Hooks/AfterClassHookMethod.cs
  TUnit.Core/Hooks/AfterTestDiscoveryHookMethod.cs
  TUnit.Core/Hooks/AfterTestHookMethod.cs
  TUnit.Core/Hooks/AfterTestSessionHookMethod.cs
  TUnit.Core/Hooks/BeforeAssemblyHookMethod.cs
  TUnit.Core/Hooks/BeforeClassHookMethod.cs
  TUnit.Core/Hooks/BeforeTestDiscoveryHookMethod.cs
  TUnit.Core/Hooks/BeforeTestHookMethod.cs
  TUnit.Core/Hooks/BeforeTestSessionHookMethod.cs
  TUnit.Core/Hooks/IExecutableHook.cs
  TUnit.Core/Hooks/InstanceHookMethod.cs
  TUnit.Core/Hooks/LastTestInAssemblyClassAdapter.cs
  TUnit.Core/Hooks/LastTestInClassAdapter.cs
  TUnit.Core/Hooks/StaticHookMethod.cs
  TUnit.Core/Interfaces/IHookExecutor.cs
  TUnit.Core/Interfaces/ITestExecutor.cs
  TUnit.Core/Interfaces/ITestStartEventReceiver.cs
  TUnit.Core/Models/SourceGenerations/SourceGeneratedClassInformation.cs
  TUnit.Core/Models/SourceGenerations/SourceGeneratedPropertyInformation.cs
  TUnit.Core/ResettableLazy.cs
  TUnit.Core/TestMetadata.cs
  TUnit.Engine/Helpers/Timings.cs
  TUnit.Engine/Services/SingleTestExecutor.cs
  TUnit.Engine/Services/TestInvoker.cs
  TUnit.Templates.Tests/Snapshots/InstantiationTest.TUnit.AspNet._.verified/TUnit.AspNet/TUnit.AspNet/TUnit.AspNet.csproj
  TUnit.Templates.Tests/Snapshots/InstantiationTest.TUnit.AspNet._.verified/TUnit.AspNet/WebApp/WebApp.csproj
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.AspNet/WebApp/WebApp.csproj
Labels: breaking

#1981 chore(deps): update tunit to 0.16.1
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, renovate-bot, MINOR

#1983 chore(deps): update tunit to 0.16.3
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#1984 chore(deps): update tunit to 0.16.4
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#1987 chore(deps): update tunit to 0.16.6
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#1993 chore(deps): update tunit to 0.16.11
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#1996 chore(deps): update tunit to 0.16.13
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2000 chore(deps): update dependency cliwrap to 3.8.2
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#2001 chore(deps): update opentelemetry to 1.11.2
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.ServiceDefaults/ExampleNamespace.ServiceDefaults.csproj
Labels: dependencies, PATCH, renovate-bot

#2005 chore(deps): update dependency opentelemetry.instrumentation.aspnetcore to 1.11.1
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.ServiceDefaults/ExampleNamespace.ServiceDefaults.csproj
Labels: dependencies, PATCH, renovate-bot

#1998 Short circuit 'Or' asserts on the first success
  TUnit.Assertions.Tests/AssertionBuilders/OrAssertionTests.cs
  TUnit.Assertions/AssertConditions/AssertionResult.cs
  TUnit.Assertions/AssertConditions/Connectors/OrAssertCondition.cs
Labels: breaking

#2008 chore(deps): update tunit to 0.16.22
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2009 chore(deps): update tunit to 0.16.23
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2016 chore(deps): update tunit to 0.16.28
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2022 chore(deps): update tunit to 0.16.36
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2026 chore(deps): update tunit to 0.16.42
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2027 chore(deps): update tunit to 0.16.45
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2030 chore(deps): update tunit to 0.16.47
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2032 chore(deps): update tunit to 0.16.50
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2035 chore(deps): update tunit to 0.16.54
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2037 chore(deps): update tunit to 0.16.56
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2044 chore(deps): update tunit to 0.17.0
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, renovate-bot, MINOR

#2045 chore(deps): update tunit to 0.17.3
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2050 chore(deps): update tunit to 0.17.11
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2051 chore(deps): update tunit to 0.17.14
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2057 chore(deps): update dependency verify.tunit to 28.14.0
  Directory.Packages.props
Labels: dependencies, renovate-bot, MINOR

#2056 chore(deps): update dependency verify.nunit to 28.14.0
  Directory.Packages.props
Labels: dependencies, renovate-bot, MINOR

#2058 Add types to help converting from one type to another during an assertion chain
  TUnit.Assertions/AssertConditions/ConvertToAssertCondition.cs
  TUnit.Assertions/AssertConditions/Interfaces/ConvertedValueSource.cs
  TUnit.Assertions/AssertionBuilders/AndConvertedTypeAssertionBuilder.cs
  TUnit.Assertions/AssertionBuilders/Groups/AndAssertionGroup.cs
  TUnit.Assertions/AssertionBuilders/Groups/OrAssertionGroup.cs
  TUnit.Assertions/AssertionBuilders/InvokableAssertionBuilder.cs
  TUnit.Assertions/AssertionBuilders/InvokableValueAssertionBuilder.cs
  TUnit.Assertions/AssertionBuilders/Wrappers/SingleItemAssertionBuilderWrapper.cs
  TUnit.Assertions/Assertions/Generics/Conditions/NoOpAssertionCondition.cs
  TUnit.Assertions/Assertions/Throws/ThrowsException.cs
  TUnit.Engine.Tests/CustomAssertionTests.cs
  TUnit.TestProject/CustomAssertions/ProblemDetailsAssertion.cs
  TUnit.TestProject/CustomAssertions/ProblemDetailsSourceGenerationContext.cs
Labels: breaking

#2059 chore(deps): update dependency microsoft.bcl.asyncinterfaces to 9.0.3
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#2060 chore(deps): update dependency microsoft.extensions.dependencyinjection to 9.0.3
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#2064 chore(deps): update microsoft.aspnetcore to 9.0.3
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/WebApp/WebApp.csproj
Labels: dependencies, PATCH, renovate-bot

#2063 chore(deps): update dependency system.text.json to 9.0.3
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#2061 chore(deps): update dependency microsoft.templateengine.authoring.templateverifier to 9.0.201
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#2065 chore(deps): update dependency microsoft.extensions.http.resilience to 9.3.0
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.ServiceDefaults/ExampleNamespace.ServiceDefaults.csproj
Labels: dependencies, renovate-bot, MINOR

#2066 chore(deps): update tunit to 0.18.0
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, renovate-bot, MINOR

#2070 chore(deps): update tunit to 0.18.9
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2073 chore(deps): update dependency verify.nunit to 28.14.1
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#2074 chore(deps): update dependency verify.tunit to 28.14.1
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#2078 chore(deps): update tunit to 0.18.17
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2080 chore(deps): update dependency verify.tunit to 28.15.0
  Directory.Packages.props
Labels: dependencies, renovate-bot, MINOR

#2079 chore(deps): update dependency verify.nunit to 28.15.0
  Directory.Packages.props
Labels: dependencies, renovate-bot, MINOR

#2082 chore(deps): update tunit to 0.18.21
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2087 chore(deps): update tunit to 0.18.23
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2089 chore(deps): update tunit to 0.18.24
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2090 chore(deps): update tunit to 0.18.26
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2096 chore(deps): update tunit to 0.18.33
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2098 chore(deps): update dependency verify.nunit to 28.16.0
  Directory.Packages.props
Labels: dependencies, renovate-bot, MINOR

#2099 chore(deps): update dependency verify.tunit to 28.16.0
  Directory.Packages.props
Labels: dependencies, renovate-bot, MINOR

#2100 chore(deps): update dependency vogen to 7.0.2
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#2102 chore(deps): update mstest to 3.8.3
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#1969 chore(deps): update microsoft.testing
  Directory.Packages.props
  TUnit.Engine.Tests/AbstractClassTests.cs
  TUnit.Engine.Tests/Attributes/SetDisplayNameWithClassAttribute.cs
  TUnit.Engine.Tests/CustomFilteringTests4.cs
  TUnit.Engine.Tests/GlobalSettings.cs
  TUnit.Engine.Tests/InvokableTestBase.cs
  TUnit.Engine.Tests/PriorityFilteringTests4.cs
  TUnit.Engine.Tests/SkipTests.cs
  TUnit.TestProject/Attributes/ClassDisplayNameAttribute.cs
Labels: dependencies, renovate-bot, MINOR

#2106 chore(deps): update tunit to 0.18.40
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2107 chore(deps): update dependency system.threading.tasks.extensions to 4.6.1
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#2108 chore(deps): update dependency streamjsonrpc to 2.21.69
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#2111 chore(deps): update dependency microsoft.playwright to 1.51.0
  Directory.Packages.props
Labels: dependencies, renovate-bot, MINOR

#2116 chore(deps): update tunit to 0.18.45
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2122 Remove duplicated code
  TUnit.Engine/Reporters/GitHubReporter.cs
Labels: ignore-for-release

#2128 chore(deps): update dependency polyfill to 7.22.0
  Directory.Packages.props
Labels: dependencies, renovate-bot, MINOR

#2135 chore(deps): update tunit to 0.18.60
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2141 chore(deps): update dependency polyfill to 7.23.0
  Directory.Packages.props
Labels: dependencies, renovate-bot, MINOR

#2152 chore(deps): update tunit to 0.19.0
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, renovate-bot, MINOR

#2153 chore(deps): update tunit to 0.19.2
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2157 chore(deps): update tunit to 0.19.4
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2158 chore(deps): update tunit to 0.19.6
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2160 chore(deps): update tunit to 0.19.10
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2163 chore(deps): update tunit to 0.19.14
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2166 chore(deps): update tunit to 0.19.17
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2173 chore(deps): update tunit to 0.19.24
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2178 chore(deps): update dependency react-dom to v19.1.0
  docs/yarn.lock
Labels: dependencies, renovate-bot, MINOR

#2177 chore(deps): update dependency react to v19.1.0
  docs/yarn.lock
Labels: dependencies, renovate-bot, MINOR

#2187 chore(deps): update tunit to 0.19.32
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#2189 chore(deps): update dependency polyfill to 7.24.0
  Directory.Packages.props
Labels: dependencies, renovate-bot, MINOR

#2191 chore(deps): update dependency verify.tunit to v29
  Directory.Packages.props
Labels: dependencies, renovate-bot, MAJOR
