Repository thomhurst/TUnit, pull requests merged in 2025-02, with the labels that each got.

#1735 chore(deps): update tunit to 0.9.6
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#1737 chore(deps): update sourcy to 0.7.4
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#1738 chore(deps): update tunit to 0.9.8
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#1740 chore(deps): update tunit to 0.9.11
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#1743 chore(deps): update sourcy to 0.7.5
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#1744 chore(deps): update tunit to 0.10.1
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, renovate-bot, MINOR

#1748 chore(deps): update tunit to 0.10.4
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#1751 chore(deps): update dependency polyfill to 7.16.1
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#1752 chore(deps): update tunit to 0.10.6
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#1753 chore(deps): update dependency microsoft.playwright to 1.50.0
  Directory.Packages.props
Labels: dependencies, renovate-bot, MINOR

#1756 chore(deps): update dependency verify.tunit to 28.10.0
  Directory.Packages.props
Labels: dependencies, renovate-bot, MINOR

#1755 chore(deps): update dependency verify.nunit to 28.10.0
  Directory.Packages.props
Labels: dependencies, renovate-bot, MINOR

#1757 chore(deps): update dependency verify.nunit to 28.10.1
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#1758 chore(deps): update dependency verify.tunit to 28.10.1
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#1759 chore(deps): update dependency messagepack to 3.1.3
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#1763 chore(deps): update sourcy to 0.7.6
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#1764 chore(deps): update tunit to 0.10.19
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#1765 chore(deps): update dependency polly to 8.5.2
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#1773 chore(deps): update tunit to 0.10.24
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#1777 chore(deps): update tunit to 0.10.26
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#1781 chore(deps): update tunit to 0.10.28
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#1788 chore(deps): update dependency xunit.runner.visualstudio to 3.0.2
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#1794 chore(deps): update tunit to 0.10.33
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#1795 Assert Conditions now contains an `AssertionMetadata` object containing delegate durations
  TUnit.Assertions/AssertConditions/BaseAssertCondition.cs
  TUnit.Assertions/AssertConditions/Connectors/AndAssertCondition.cs
  TUnit.Assertions/AssertConditions/Connectors/OrAssertCondition.cs
  TUnit.Assertions/AssertConditions/DelegateAssertCondition.cs
  TUnit.Assertions/AssertConditions/EnumerableSatisfiesAssertCondition.cs
  TUnit.Assertions/AssertConditions/ExpectedValueAssertCondition.cs
  TUnit.Assertions/AssertConditions/NotNullExpectedValueAssertCondition.cs
  TUnit.Assertions/AssertConditions/NullExpectedValueAssertCondition.cs
  TUnit.Assertions/AssertConditions/SatisfiesAssertCondition.cs
  TUnit.Assertions/AssertConditions/ValueAssertCondition.cs
  TUnit.Assertions/AssertionBuilders/AssertionBuilder.cs
  TUnit.Assertions/AssertionData.cs
  TUnit.Assertions/AssertionMetadata.cs
  TUnit.Assertions/Assertions/Collections/Conditions/EnumerableAllExpectedFuncAssertCondition.cs
  TUnit.Assertions/Assertions/Collections/Conditions/EnumerableContainsExpectedFuncAssertCondition.cs
  TUnit.Assertions/Assertions/Collections/Conditions/EnumerableDistinctItemsExpectedValueAssertCondition.cs
  TUnit.Assertions/Assertions/Collections/Conditions/EnumerableNotContainsExpectedFuncAssertCondition.cs
  TUnit.Assertions/Assertions/Collections/Conditions/EnumerableOrderedByAssertCondition.cs
  TUnit.Assertions/Assertions/Comparables/Conditions/BetweenAssertCondition.cs
  TUnit.Assertions/Assertions/Comparables/Conditions/NotBetweenAssertCondition.cs
  TUnit.Assertions/Assertions/Enums/Conditions/EnumDoesNotHaveFlagAssertCondition.cs
  TUnit.Assertions/Assertions/Enums/Conditions/EnumDoesNotHaveSameNameAsCondition.cs
  TUnit.Assertions/Assertions/Enums/Conditions/EnumDoesNotHaveSameValueAsCondition.cs
  TUnit.Assertions/Assertions/Enums/Conditions/EnumHasFlagAssertCondition.cs
  TUnit.Assertions/Assertions/Enums/Conditions/EnumHasSameNameAsCondition.cs
  TUnit.Assertions/Assertions/Enums/Conditions/EnumHasSameValueAsCondition.cs
  TUnit.Assertions/Assertions/Enums/Conditions/EnumIsDefinedAssertCondition.cs
  TUnit.Assertions/Assertions/Enums/Conditions/EnumIsNotDefinedAssertCondition.cs
  TUnit.Assertions/Assertions/Generics/Conditions/AssignableFromExpectedValueAssertCondition.cs
  TUnit.Assertions/Assertions/Generics/Conditions/AssignableToExpectedValueAssertCondition.cs
  TUnit.Assertions/Assertions/Generics/Conditions/DefaultAssertionCondition.cs
  TUnit.Assertions/Assertions/Generics/Conditions/NoOpWithMessageAssertionCondition.cs
  TUnit.Assertions/Assertions/Generics/Conditions/NotAssignableFromExpectedValueAssertCondition.cs
  TUnit.Assertions/Assertions/Generics/Conditions/NotAssignableToExpectedValueAssertCondition.cs
  TUnit.Assertions/Assertions/Generics/Conditions/NotTypeOfExpectedValueAssertCondition.cs
  TUnit.Assertions/Assertions/Generics/Conditions/TypeOfExpectedValueAssertCondition.cs
  TUnit.Assertions/Assertions/Throws/ThrowsAnyExceptionAssertCondition.cs
  TUnit.Assertions/Assertions/Throws/ThrowsExactlyAssertCondition.cs
  TUnit.Assertions/Assertions/Throws/ThrowsException.cs
  TUnit.Assertions/Assertions/Throws/ThrowsNothingAssertCondition.cs
  TUnit.Assertions/Assertions/Throws/ThrowsOfTypeAssertCondition.cs
  TUnit.Assertions/Assertions/Throws/ThrowsWithMessageAssertCondition.cs
  TUnit.Assertions/Assertions/Throws/ThrowsWithMessageMatchingAssertCondition.cs
  TUnit.Assertions/Assertions/Throws/ThrowsWithParamNameAssertCondition.cs
  TUnit.Assertions/Extensions/DelegateExtensions.cs
Labels: breaking

#1799 chore(deps): update tunit to 0.11.0
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, renovate-bot, MINOR

#1802 chore(deps): update dependency microsoft.net.test.sdk to 17.13.0
  Directory.Packages.props
Labels: dependencies, renovate-bot, MINOR

#1803 chore(deps): update dependency testcontainers.postgresql to 4.2.0
  Directory.Packages.props
Labels: dependencies, renovate-bot, MINOR

#1804 chore(deps): update dependency testcontainers.redis to 4.2.0
  Directory.Packages.props
Labels: dependencies, renovate-bot, MINOR

#1806 chore(deps): update dependency microsoft.build.utilities.core to 17.13.9
  Directory.Packages.props
Labels: dependencies, renovate-bot, MINOR

#1807 chore(deps): update dependency microsoft.bcl.asyncinterfaces to 9.0.2
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#1810 chore(deps): update dependency microsoft.aspnetcore.openapi to 8.0.13
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/WebApp/WebApp.csproj
Labels: dependencies, PATCH, renovate-bot

#1809 chore(deps): update dependency microsoft.aspnetcore.mvc.testing to 8.0.13
  TUnit.Templates/content/TUnit.AspNet/WebApp/WebApp.csproj
Labels: dependencies, PATCH, renovate-bot

#1812 chore(deps): update dependency microsoft.extensions.dependencyinjection to 9.0.2
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#1811 chore(deps): update dependency microsoft.aspnetcore.testhost to 9.0.2
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#1813 chore(deps): update dependency system.text.json to 9.0.2
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#1816 chore(deps): update tunit to 0.12.0
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, renovate-bot, MINOR

#1824 chore(deps): update mstest to 3.8.0
  Directory.Packages.props
Labels: dependencies, renovate-bot, MINOR

#1826 chore(deps): update tunit to 0.12.6
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#1827 chore(deps): update dependency streamjsonrpc to 2.21.10
  Directory.Packages.props
Labels: dependencies, renovate-bot, MINOR

#1830 chore(deps): update dependency cliwrap to 3.8.0
  Directory.Packages.props
Labels: dependencies, renovate-bot, MINOR

#1832 chore(deps): update dependency vogen to v7
  Directory.Packages.props
Labels: dependencies, renovate-bot, MAJOR

#1834 chore(deps): update tunit to 0.12.11
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#1835 chore(deps): update tunit to 0.12.13
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#1840 chore(deps): update tunit to 0.12.14
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#1843 chore(deps): update tunit to 0.12.17
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#1846 chore(deps): update dependency verify.nunit to 28.11.0
  Directory.Packages.props
Labels: dependencies, renovate-bot, MINOR

#1847 chore(deps): update dependency verify.tunit to 28.11.0
  Directory.Packages.props
Labels: dependencies, renovate-bot, MINOR

#1849 chore(deps): update tunit to 0.12.21
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#1852 chore(deps): update tunit to 0.12.23
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#1858 chore(deps): update tunit to 0.12.25
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#1868 Use TextWriter.Synchronized for Thread Safe Test Output
  TUnit.Core/Context.cs
  TUnit.Core/Interfaces/IContext.cs
  TUnit.Core/Logging/ThreadSafeStringWriter.cs
  TUnit.Engine/Logging/ConsoleInterceptor.cs
  TUnit.Engine/Logging/StandardErrorConsoleInterceptor.cs
  TUnit.Engine/Logging/StandardOutConsoleInterceptor.cs
Labels: breaking

#1866 chore(deps): update tunit to 0.13.0
  Directory.Packages.props
  TUnit.Pipeline/Modules/RunTemplateTestsModule.cs
  TUnit.Templates.Tests/Snapshots/InstantiationTest.TUnit.AspNet._.verified/TUnit.AspNet/TUnit.AspNet/TUnit.AspNet.csproj
  TUnit.Templates.Tests/Snapshots/InstantiationTest.TUnit.Playwright._.verified/TUnit.Playwright/TUnit.Playwright.csproj
  TUnit.Templates.Tests/Snapshots/InstantiationTest.TUnit._.verified/TUnit/TUnit.csproj
  TUnit.Templates.Tests/TemplateTestBase.cs
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
  renovate.json
Labels: dependencies, renovate-bot, MINOR

#1873 chore(deps): update tunit to 0.13.3
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#1879 chore(deps): update tunit to 0.13.9
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#1886 chore(deps): update modularpipelines to 2.42.319
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#1891 chore(deps): update mstest to 3.8.1
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#1892 chore(deps): update tunit to 0.13.18
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#1895 chore(deps): update mstest to 3.8.2
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#1898 chore(deps): update tunit to 0.13.20
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#1897 Add tests for PrintMembers issue
  TUnit.Engine.Tests/ConsoleTests.cs
  TUnit.TestProject/ConsoleTests.cs
Labels: ignore-for-release

#1901 chore(deps): update tunit to 0.13.23
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#1467 Strong name the assemblies in this package
  Directory.Build.targets
  TUnit.Assertions.Analyzers.CodeFixers/TUnit.Assertions.Analyzers.CodeFixers.csproj
  TUnit.Assertions.Analyzers/Properties/AssemblyInfo.cs
  TUnit.Assertions.Analyzers/TUnit.Assertions.Analyzers.csproj
  TUnit.Core.SourceGenerator.Tests/TUnit.Core.SourceGenerator.Tests.csproj
  TUnit.Engine.Tests/TUnit.Engine.Tests.csproj
  TUnit.Pipeline/TUnit.Pipeline.csproj
  strongname.snk
Labels: breaking

#1904 chore(deps): update tunit to 0.14.0
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, renovate-bot, MINOR

#1909 chore(deps): update dependency polyfill to 7.18.0
  Directory.Packages.props
Labels: dependencies, renovate-bot, MINOR

#1913 chore(deps): update tunit to 0.14.6
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#1918 chore(deps): update dependency cliwrap to 3.8.1
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#1919 chore(deps): update dependency verify.nunit to 28.12.0
  Directory.Packages.props
Labels: dependencies, renovate-bot, MINOR

#1920 chore(deps): update dependency verify.tunit to 28.12.0
  Directory.Packages.props
Labels: dependencies, renovate-bot, MINOR

#1925 chore(deps): update dependency testcontainers.postgresql to 4.3.0
  Directory.Packages.props
Labels: dependencies, renovate-bot, MINOR

#1927 chore(deps): update modularpipelines to 2.43.0
  Directory.Packages.props
Labels: dependencies, renovate-bot, MINOR

#1930 chore(deps): update dependency verify.nunit to 28.12.1
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#1933 chore(deps): update tunit
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot, MINOR

#1946 Flow AsyncLocal Values between Hooks + Tests via `context.AddAsyncLocalValues()`
  TUnit.Analyzers.Tests/BeforeHookAsyncLocalAnalyzerTests.cs
  TUnit.Analyzers/BeforeHookAsyncLocalAnalyzer.cs
  TUnit.Analyzers/Resources.Designer.cs
  TUnit.Analyzers/Resources.resx
  TUnit.Analyzers/Rules.cs
  TUnit.Core.SourceGenerator.Tests/AfterAllTests.Test.verified.txt
  TUnit.Core.SourceGenerator.Tests/AfterTests.Test.verified.txt
  TUnit.Core.SourceGenerator.Tests/AssemblyAfterTests.Test.verified.txt
  TUnit.Core.SourceGenerator.Tests/AssemblyBeforeTests.Test.verified.txt
  TUnit.Core.SourceGenerator.Tests/BeforeAllTests.Test.verified.txt
  TUnit.Core.SourceGenerator.Tests/BeforeTests.Test.verified.txt
  TUnit.Core.SourceGenerator.Tests/GlobalStaticAfterEachTests.Test.verified.txt
  TUnit.Core.SourceGenerator.Tests/GlobalStaticBeforeEachTests.Test.verified.txt
  TUnit.Core.SourceGenerator.Tests/Hooks1589.Test.verified.txt
  TUnit.Core.SourceGenerator.Tests/Hooks1594.Test.verified.txt
  TUnit.Core.SourceGenerator.Tests/STAThreadHooksTests.Test.verified.txt
  TUnit.Core.SourceGenerator.Tests/TestDiscoveryHookTests.Test.verified.txt
  TUnit.Core.SourceGenerator.Tests/Tests1899.BaseClass.verified.txt
  TUnit.Core.SourceGenerator/CodeGenerators/Writers/Hooks/AssemblyHooksWriter.cs
  TUnit.Core.SourceGenerator/CodeGenerators/Writers/Hooks/ClassHooksWriter.cs
  TUnit.Core.SourceGenerator/CodeGenerators/Writers/Hooks/GlobalTestHooksWriter.cs
  TUnit.Core.SourceGenerator/CodeGenerators/Writers/Hooks/TestHooksWriter.cs
  TUnit.Core/AsyncConvert.cs
  TUnit.Core/Context.cs
  TUnit.Core/Extensions/TestContextExtensions.cs
  TUnit.Core/Hooks/AfterAssemblyHookMethod.cs
  TUnit.Core/Hooks/AfterClassHookMethod.cs
  TUnit.Core/Hooks/AfterTestDiscoveryHookMethod.cs
  TUnit.Core/Hooks/AfterTestHookMethod.cs
  TUnit.Core/Hooks/AfterTestSessionHookMethod.cs
  TUnit.Core/Hooks/BeforeAssemblyHookMethod.cs
  TUnit.Core/Hooks/BeforeClassHookMethod.cs
  TUnit.Core/Hooks/BeforeTestDiscoveryHookMethod.cs
  TUnit.Core/Hooks/BeforeTestHookMethod.cs
  TUnit.Core/Hooks/BeforeTestSessionHookMethod.cs
  TUnit.Core/Hooks/IExecutableHook.cs
  TUnit.Core/Hooks/InstanceHookMethod.cs
  TUnit.Core/Hooks/StaticHookMethod.cs
  TUnit.Engine/Extensions/TestContextExtensions.cs
  TUnit.Engine/Framework/TUnitServiceProvider.cs
  TUnit.Engine/Framework/TUnitTestFramework.cs
  TUnit.Engine/Helpers/ExecutionContextHelper.cs
  TUnit.Engine/Hooks/AssemblyHookOrchestrator.cs
  TUnit.Engine/Hooks/ClassHookOrchestrator.cs
  TUnit.Engine/Hooks/TestDiscoveryHookOrchestrator.cs
  TUnit.Engine/Hooks/TestHookOrchestrator.cs
  TUnit.Engine/Hooks/TestSessionHookOrchestrator.cs
  TUnit.Engine/Services/HooksCollector.cs
  TUnit.Engine/Services/SingleTestExecutor.cs
  TUnit.Engine/Services/TUnitTestDiscoverer.cs
  TUnit.Engine/Services/TestInvoker.cs
  TUnit.Engine/Services/TestsExecutor.cs
  TUnit.Engine/Services/TestsFinder.cs
  TUnit.Engine/TUnitMessageBus.cs
  TUnit.TestProject/AsyncLocalTest.cs
  TUnit.TestProject/Bugs/1914/AsyncHookTests.cs
  TUnit.TestProject/Bugs/1914/SyncHookTests.cs
  docs/docs/tutorial-extras/setup.md
Labels: enhancement, breaking

#1952 chore(deps): update dependency microsoft.aspnetcore.mvc.testing to 9.0.2
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#1953 chore(deps): update dependency vogen to 7.0.1
  Directory.Packages.props
Labels: dependencies, PATCH, renovate-bot

#1931 chore(deps): update microsoft.extensions
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.ServiceDefaults/ExampleNamespace.ServiceDefaults.csproj
Labels: dependencies, renovate-bot, MINOR

#1484 chore(deps): update microsoft.testing
  Directory.Packages.props
  TUnit.Engine.Tests/AbstractClassTests.cs
  TUnit.Engine.Tests/CustomFilteringTests4.cs
  TUnit.Engine.Tests/PriorityFilteringTests4.cs
  TUnit.Engine.Tests/SkipTests.cs
Labels: dependencies, renovate-bot, MINOR

#1960 chore(deps): update dependency polyfill to 7.20.0
  Directory.Packages.props
Labels: dependencies, renovate-bot, MINOR

#1962 chore(deps): update opentelemetry
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.ServiceDefaults/ExampleNamespace.ServiceDefaults.csproj
Labels: dependencies, renovate-bot, MINOR

#1961 chore(deps): update dependency verify.nunit to 28.13.0
  Directory.Packages.props
Labels: dependencies, renovate-bot, MINOR

#1963 chore(deps): update tunit
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, renovate-bot, MINOR

#1967 chore(deps): update dependency typescript to ~5.8.0
  docs/package.json
  docs/yarn.lock
Labels: dependencies, renovate-bot, MINOR

#1965 chore(deps): update tunit to 0.15.18
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot

#1970 chore(deps): update tunit to 0.15.30
  Directory.Packages.props
  TUnit.Templates/content/TUnit.AspNet/TestProject/TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Starter/ExampleNamespace.TestProject/ExampleNamespace.TestProject.csproj
  TUnit.Templates/content/TUnit.Aspire.Test/ExampleNamespace.csproj
  TUnit.Templates/content/TUnit.Playwright/TestProject.csproj
  TUnit.Templates/content/TUnit/TestProject.csproj
Labels: dependencies, PATCH, renovate-bot
